package org.BotSasSE.botComands.enums;

public enum ConversationState {
    CONVERSATION_STARTED,
    WAITING_FOR_COMMAND,
    WAITING_FOR_NAME,
    WAITING_FOR_ADVANCE,
    WAITING_FOR_PeselNumber,
    WAITING_FOR_Passport,
    WAITING_FOR_INPUT_PeselNumber,
    WAITING_FOR_DAY,
    WAITING_FOR_YEAR,
    WAITING_FOR_MONTH,
    WAITING_FOR_HOURS,
    WAITING_FOR_TEXT,
    WAITING_FOR_NEXT_STEP,
    WAITING_FOR_SURNAME_PHOTO,
    WAITING_FOR_PHOTO,
    WAITING_FOR_SALARY_YEAR,
    WAITING_FOR_SALARY_MONTH,
    GETTING_CALCULATION,
    WAITING_FOR_GET_CALCULATION,
    WAITING_FOR_MONTH_PHOTO


}
